lightgbm:
  objective: multiclass
  num_class: 3
  metric: multi_logloss
  boosting_type: gbdt
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 1

training:
  n_splits: 5
  num_boost_round: 1000
  early_stopping_rounds: 50

